StartupEvents.registry('item', event => {
//MIEDZIANE BRONIE
event.create('copper_hammer', 'sword')
    .maxStackSize(1)
    .displayName("Copper Hammer")
    .maxDamage(190)
    .attackDamageBaseline(6)
    .attackDamageBonus(1)
    .speedBaseline(-3.3)
    .texture('kubejs:item/copper_hammer')

event.create('copper_dagger', 'sword')
    .maxStackSize(1)
    .displayName("Copper Dagger")
    .maxDamage(190)
    .attackDamageBaseline(1)
    .attackDamageBonus(1)
    .speedBaseline(-2.0)
    .texture('kubejs:item/copper_dagger')

event.create('copper_club', 'sword')
    .maxStackSize(1)
    .displayName("Copper Club")
    .maxDamage(190)
    .attackDamageBaseline(5)
    .attackDamageBonus(1)
    .speedBaseline(-3.0)
    .texture('kubejs:item/copper_club')

event.create('copper_spear', 'sword')
    .maxStackSize(1)
    .displayName("Copper Spear")
    .maxDamage(190)
    .attackDamageBaseline(3)
    .attackDamageBonus(1)
    .speedBaseline(-2.7)
    .texture('kubejs:item/copper_spear_held')

event.create('copper_quarterstaff', 'sword')
    .maxStackSize(1)
    .displayName("Copper Quarterstaff")
    .maxDamage(190)
    .attackDamageBaseline(1)
    .attackDamageBonus(1)
    .speedBaseline(-2.3)
    .texture('kubejs:item/copper_quarterstaff_held')

//STALOWE BRONIE
event.create('steel_hammer', 'sword')
    .maxStackSize(1)
    .displayName("Steel Hammer")
    .maxDamage(500)
    .attackDamageBaseline(8)
    .attackDamageBonus(1)
    .speedBaseline(-3.3)
    .texture('kubejs:item/steel_hammer')

event.create('steel_dagger', 'sword')
    .maxStackSize(1)
    .displayName("Steel Dagger")
    .maxDamage(500)
    .attackDamageBaseline(5)
    .attackDamageBonus(1)
    .speedBaseline(-2.0)
    .texture('kubejs:item/steel_dagger')

event.create('steel_club', 'sword')
    .maxStackSize(1)
    .displayName("Steel Club")
    .maxDamage(500)
    .attackDamageBaseline(7)
    .attackDamageBonus(1)
    .speedBaseline(-3.0)
    .texture('kubejs:item/steel_club')

event.create('steel_spear', 'sword')
    .maxStackSize(1)
    .displayName("Steel Spear")
    .maxDamage(500)
    .attackDamageBaseline(3)
    .attackDamageBonus(1)
    .speedBaseline(-2.7)
    .texture('kubejs:item/steel_spear')

event.create('steel_quarterstaff', 'sword')
    .maxStackSize(1)
    .displayName("steel Quarterstaff")
    .maxDamage(500)
    .attackDamageBaseline(3)
    .attackDamageBonus(1)
    .speedBaseline(-2.3)
    .texture('kubejs:item/steel_quarterstaff_held')

})