! Put your rules here in the format:
! old_biome > new_biome
! 
! Examples (remove ! in front of one to activate it):
terralith:steppe > minecraft:plains
terralith:sakura_grove > biomeswevegone:sakura_grove
terralith:orchid_swamp > environmental:marsh
terralith:shrubland > null
terralith:lush_desert > atmospheric:flourishing_dunes
terralith:hot_shrubland > null