! Put your rules here in the format:
! old_biome > new_biome
! 
! Examples (remove ! in front of one to activate it):
terralith:steppe > minecraft:plains
terralith:sakura_grove > biomeswevegone:sakura_grove
terralith:orchid_swamp > environmental:marsh
terralith:shrubland > null
terralith:lush_desert > atmospheric:flourishing_dunes
terralith:hot_shrubland > null
terralith:cave/diorite_caves > galosphere:lichen_caves
terralith:cave/desert_caves > yungscavebiomes:lost_caves
terralith:cave/ice_caves > yungscavebiomes:frosted_caves
minecraft:wooded_badlands > terralith:bryce_canyon
minecraft:old_growth_birch_forest > biomeswevegone:overgrowth_woodlands
terralith:forested_highlands > biomeswevegone:redwood_thicket
terralith:lavender_forest > biomeswevegone:forgotten_forest
terralith:tropical_jungle > biomeswevegone:tropical_rainforest